// ObjcMarkdownViewer
// SPDX-License-Identifier: GPL-2.0-or-later

#include <sys/types.h>
#if defined(_WIN32) && !defined(_MODE_T_)
#define _MODE_T_
typedef unsigned short mode_t;
#endif
#import <AppKit/AppKit.h>
#import "OMDSourceTextView.h"

@class OMMarkdownRenderer;
@class OMDDocumentConverter;
@class OMDLineNumberRulerView;
@class OMDFormattingBarView;
@class GSVVimBindingController;
@class OMDGitHubClient;

@interface OMDAppDelegate : NSObject <NSApplicationDelegate, NSToolbarDelegate, NSWindowDelegate, NSTextViewDelegate, NSMenuValidation, NSSplitViewDelegate, NSTableViewDataSource, NSTableViewDelegate, NSComboBoxDelegate, NSControlTextEditingDelegate, OMDSourceTextViewVimEventHandling>
{
    NSWindow *_window;
    NSSplitView *_workspaceSplitView;
    NSView *_workspaceMainContainer;
    NSView *_sidebarContainer;
    NSView *_tabStripView;
    NSView *_documentContainer;
    NSSplitView *_splitView;
    NSScrollView *_previewScrollView;
    NSView *_previewCanvasView;
    NSScrollView *_sourceScrollView;
    NSView *_sourceEditorContainer;
    OMDFormattingBarView *_formattingBarView;
    NSTextView *_textView;
    NSTextView *_sourceTextView;
    OMDLineNumberRulerView *_sourceLineNumberRuler;
    OMMarkdownRenderer *_renderer;
    BOOL _openedFileOnLaunch;
    NSString *_currentMarkdown;
    NSString *_currentPath;
    NSString *_currentDisplayTitle;
    NSString *_currentLoadedDiskFingerprint;
    NSString *_currentObservedDiskFingerprint;
    NSString *_currentSuppressedDiskFingerprint;
    NSInteger _currentDocumentRenderMode;
    NSString *_currentDocumentSyntaxLanguage;
    BOOL _currentDocumentReadOnly;
    NSMutableArray *_documentTabs;
    NSInteger _selectedDocumentTabIndex;
    OMDGitHubClient *_gitHubClient;
    NSMenu *_fileOpenRecentMenu;
    NSMenuItem *_viewShowExplorerMenuItem;
    NSControl *_explorerSourceModeControl;
    NSTextField *_explorerLocalRootLabel;
    NSTextField *_explorerGitHubUserLabel;
    NSComboBox *_explorerGitHubUserComboBox;
    NSComboBox *_explorerGitHubRepoComboBox;
    NSButton *_explorerGitHubIncludeForkArchivedButton;
    NSButton *_explorerShowHiddenFilesButton;
    NSButton *_explorerNavigateUpButton;
    NSTextField *_explorerPathLabel;
    NSScrollView *_explorerScrollView;
    NSTableView *_explorerTableView;
    NSMutableArray *_explorerEntries;
    NSArray *_explorerGitHubRepos;
    NSString *_explorerLocalRootPath;
    NSString *_explorerLocalCurrentPath;
    NSString *_explorerGitHubUser;
    NSString *_explorerGitHubRepo;
    NSString *_explorerGitHubCurrentPath;
    NSString *_explorerGitHubRepoCachePath;
    NSInteger _explorerSourceMode;
    NSUInteger _explorerRequestToken;
    BOOL _explorerIsLoading;
    BOOL _explorerSidebarVisible;
    CGFloat _explorerSidebarLastVisibleWidth;
    NSView *_toolbarPrimaryActionsContainer;
    NSSegmentedControl *_toolbarFileActionsControl;
    NSSegmentedControl *_toolbarUtilityActionsControl;
    NSSlider *_zoomSlider;
    NSTextField *_zoomLabel;
    NSButton *_zoomResetButton;
    NSView *_zoomContainer;
    CGFloat _zoomScale;
    NSTimer *_interactiveRenderTimer;
    NSTimer *_mathArtifactRenderTimer;
    NSTimer *_livePreviewRenderTimer;
    NSTimer *_previewStatusUpdatingDelayTimer;
    NSTimer *_previewStatusAutoHideTimer;
    NSTimer *_linkedScrollDriverResetTimer;
    NSTimer *_sourceSyntaxHighlightTimer;
    NSTimer *_recoveryAutosaveTimer;
    NSTimer *_externalFileMonitorTimer;
    NSTimer *_copyFeedbackTimer;
    NSMutableArray *_codeBlockButtons;
    NSButton *_copyFeedbackButton;
    NSView *_copyFeedbackHUDView;
    BOOL _isSecondaryWindow;
    OMDDocumentConverter *_documentConverter;
    GSVVimBindingController *_sourceVimBindingController;
    NSView *_modeContainer;
    NSSegmentedControl *_modeControl;
    NSTextField *_modeLabel;
    NSTextField *_previewStatusLabel;
    NSMenuItem *_viewShowFormattingBarMenuItem;
    NSSegmentedControl *_formatHeadingControl;
    NSMutableDictionary *_formatCommandButtons;
    NSPanel *_preferencesPanel;
    NSSegmentedControl *_preferencesSectionControl;
    NSPopUpButton *_preferencesMathPolicyPopup;
    NSPopUpButton *_preferencesSplitSyncModePopup;
    NSPopUpButton *_preferencesThemePopup;
    NSPopUpButton *_preferencesLayoutModePopup;
    NSSlider *_preferencesScrollSpeedSlider;
    NSButton *_preferencesAllowRemoteImagesButton;
    NSButton *_preferencesFormattingBarButton;
    NSButton *_preferencesWordSelectionShimButton;
    NSButton *_preferencesSourceVimKeyBindingsButton;
    NSButton *_preferencesSyntaxHighlightingButton;
    NSButton *_preferencesSourceHighContrastButton;
    NSColorWell *_preferencesSourceAccentColorWell;
    NSButton *_preferencesSourceAccentResetButton;
    NSButton *_preferencesRendererSyntaxHighlightingButton;
    NSTextField *_preferencesRendererSyntaxHighlightingNoteLabel;
    NSTextField *_preferencesExplorerLocalRootField;
    NSTextField *_preferencesExplorerMaxFileSizeField;
    NSTextField *_preferencesExplorerListFontSizeField;
    NSSecureTextField *_preferencesExplorerGitHubTokenField;
    NSInteger _preferencesSelectedSection;
    NSInteger _viewerMode;
    CGFloat _splitRatio;
    CGFloat _lastObservedSplitAvailableWidth;
    BOOL _isProgrammaticSourceUpdate;
    BOOL _isProgrammaticSourceHighlightUpdate;
    BOOL _isProgrammaticSelectionSync;
    BOOL _isProgrammaticPreviewUpdate;
    BOOL _isProgrammaticScrollSync;
    BOOL _isApplyingSplitViewRatio;
    BOOL _previewStatusUpdatingVisible;
    BOOL _previewStatusShowsUpdated;
    BOOL _previewIsUpdating;
    BOOL _sourceHighlightNeedsFullPass;
    BOOL _showFormattingBar;
    BOOL _zoomUsesDebouncedRendering;
    BOOL _sourceIsDirty;
    BOOL _sourceVimForceClose;
    NSUInteger _sourceRevision;
    NSUInteger _lastRenderedSourceRevision;
    NSUInteger _zoomFastRenderStreak;
    NSTimeInterval _lastZoomSliderEventTime;
    CGFloat _lastRenderedLayoutWidth;
    NSInteger _activeLinkedScrollDriver;
    NSString *_sourceVimCommandLine;
    BOOL _externalReloadPromptVisible;
}

@end
